<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Market\IndexController'                    => __DIR__ . '/src/Market/Controller/IndexController.php',
    'ZendSkeletonModuleTest\SampleTest'         => __DIR__ . '/tests/Market/SampleTest.php',
    'ZendSkeletonModuleTest\Framework\TestCase' => __DIR__ . '/tests/Market/Framework/TestCase.php',
    'Market\Module'                             => __DIR__ . '/Module.php',
);
