<h1>Item</h1>
<?php if($this->item){?>
    <h3>
        <?php echo $this->escapeHtml(ucwords($this->item->title));?>
    </h3>

<div style="width: 250px; float: left">
    <?php if($this->item->photo_filename){ ?>
        <img src="<?php echo $this->escapeHtml($this->item->photo_filename); ?>">
    <?php }else{ ?>
        No Image
    <?php } ?>
</div>

<div style="width: 400px; float: left; margin: 20px">
    <b>Contact Details</b>
    <br>Name: <?php echo $this->escapeHtml($this->item->contact_name);?>
    <br>Email: <?php echo $this->escapeHtml($this->item->contact_email);?>
    <br>Phone: <?php echo $this->escapeHtml($this->item->contact_phone);?>
    <br><b>Postings Details</b>
    <br>Created: <?php echo $this->escapeHtml($this->item->date_created);?>
    <br>Price: <?php echo $this->escapeHtml($this->item->price);?>
    <br>City: <?php echo $this->escapeHtml($this->item->city);?>, <?php $this->escapeHtml($this->item->country);?>
    <br><b>Description</b>
    <br><p><?php echo $this->escapeHtml($this->item->description);?></p>
</div>
<?php }else{  ?>
    No Recent Postings

<?php } ?>